#!/bin/bash

# install traefik
./traefik/install
./traefik/wait

# get a public IP
external_ip=""
while [ -z "${external_ip}" ]; do
  external_ip=$(kubectl get service --all-namespaces --field-selector='metadata.name=traefik' \
    --output jsonpath='{.items[].status.loadBalancer.ingress[?(@.ip != "")].ip}')
done

echo "Will use public IP address ${external_ip}"

kubectl apply -f namespace.yaml

# install quarks
./quarks/install

# install gitea
./gitea/install "$external_ip"

# install container-registry
./container-registry/install

# install kpack
./kpack/install

# install drone
./drone/install "$external_ip"

# install eirini
./eirini/install "${external_ip}"

# configure drone
./drone-gitea/install "$external_ip"
