---
# NAMESPACE
apiVersion: v1
kind: Namespace
metadata:
    name: eirini-workloads
---
# BUILD
apiVersion: v1
kind: Secret
metadata:
  name: git-creds
  namespace: eirini-workloads
  annotations:
    kpack.io/git: "http://gitea.{{PUBLIC_IP}}.nip.io"
type: kubernetes.io/basic-auth
stringData:
  username: dev
  password: changeme
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-serviceaccount
  namespace: eirini-workloads
secrets:
- name: git-creds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eirini
  namespace: eirini-workloads
