#!/bin/bash

function log() {
  echo -e "\e[35mquarks> \e[32m$1\e[39m"
}

log "Adding quarks repo to helm."
helm repo add quarks https://cloudfoundry-incubator.github.io/quarks-helm/ >> "$HOME/.carrier.log"

log "Creating quarks namespace."
kubectl create namespace quarks >> "$HOME/.carrier.log"

log "Installing quarks-secret."
helm install quarks-secret quarks/quarks-secret \
  --wait \
  --version 1.0.752 \
  --namespace quarks \
  --set "global.monitoredID=carrier" \
  >> "$HOME/.carrier.log"

log "Installing quarks-job."
helm install quarks-job quarks/quarks-job \
  --wait \
  --version 1.0.211 \
  --namespace quarks \
  --set "global.monitoredID=carrier" \
  >> "$HOME/.carrier.log"
