apiVersion: v1
kind: Secret
metadata:
  name: container-registry-config
  namespace: default
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |-
    { "insecure-registries": ["container-registry.carrier.svc"] }
