#!/bin/bash

function log() {
  echo -e "\e[35mkpack> \e[32m$1\e[39m"
}

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

log "Setting up container registry config for kpack."
kubectl apply -f "$dir/container-registry-config.yaml" >> "$HOME/.carrier.log"

log "Creating a service account for kpack."
kubectl apply -f "$dir/service-account.yaml" >> "$HOME/.carrier.log"

log "Installing kpack."
kubectl apply -f "$dir/release-0.1.2.yaml" >> "$HOME/.carrier.log"

log "Waiting for webhook to come online."
retry 60 'kubectl wait --for=condition=Ready --timeout=5s -n kpack --selector=app=kpack-webhook pod' >> "$HOME/.carrier.log" 2>&1

log "Setting up a kpack store."
kubectl apply -f "$dir/store.yaml" >> "$HOME/.carrier.log"

log "Setting up a kpack stack."
kubectl apply -f "$dir/stack.yaml" >> "$HOME/.carrier.log"

log "Creating a kpack builder."
kubectl apply -f "$dir/builder.yaml" >> "$HOME/.carrier.log"
